CREATE TABLE rating (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id BIGINT NOT NULL,
    rater_id   BIGINT NOT NULL,
    ratee_id   BIGINT NOT NULL,
    score      SMALLINT NOT NULL,
    comment    VARCHAR(500),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_rating_mission FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE,
    CONSTRAINT fk_rating_rater FOREIGN KEY (rater_id) REFERENCES users (id),
    CONSTRAINT fk_rating_ratee FOREIGN KEY (ratee_id) REFERENCES users (id),
    -- one rating per rater per mission: this is what makes a rating final
    CONSTRAINT rating_mission_rater_unique UNIQUE (mission_id, rater_id),
    CONSTRAINT rating_score_check CHECK (score BETWEEN 1 AND 5)
);

-- Profile lookups are all "ratings received by this user".
CREATE INDEX idx_rating_ratee ON rating (ratee_id);
