-- Audit trail: one immutable row per state-changing user action — who (actor),
-- did what (action), to what (target), when. Insert-only, so no updated_at.
-- The actor is a real FK with no cascade: users are never deleted, and history
-- must never be erasable through a user row. The target is a (type, id) pair,
-- not an FK — missions are deletable and bids withdrawable, and the history has
-- to outlive them; `details` snapshots the human-readable context instead.
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT NOT NULL,
    actor_role  VARCHAR(16) NOT NULL,
    action      VARCHAR(32) NOT NULL,
    target_type VARCHAR(16) NOT NULL,
    target_id   BIGINT NOT NULL,
    details     VARCHAR(500),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT audit_log_actor_role_check CHECK (actor_role IN ('DESIGNER', 'PILOT', 'ADMIN')),
    CONSTRAINT audit_log_target_type_check CHECK (target_type IN ('MISSION', 'BID', 'USER', 'RATING')),
    CONSTRAINT audit_log_action_check CHECK (action IN (
        'MISSION_CREATED', 'MISSION_UPDATED', 'MISSION_DELETED', 'MISSION_STARTED',
        'MISSION_COMPLETED', 'MISSION_CANCELLED', 'MISSION_HIDDEN', 'MISSION_UNHIDDEN',
        'MISSION_REMOVED', 'MISSION_RESTORED',
        'BID_PLACED', 'BID_WITHDRAWN', 'BID_ACCEPTED',
        'USER_REGISTERED', 'USER_LOGGED_IN', 'USER_SUSPENDED', 'USER_REACTIVATED',
        'RATING_CREATED'))
);

-- The admin listing is always newest-first; the actor filter narrows the same path.
CREATE INDEX idx_audit_log_created ON audit_log (created_at DESC);
CREATE INDEX idx_audit_log_actor_created ON audit_log (actor_id, created_at DESC);
