-- Baseline schema for the mission table.
-- Mirrors the entity com.project.drone_missions.model.Mission. On databases that
-- predate Flyway this script is not executed (Flyway stamps them as the V1
-- baseline); on fresh databases it creates the schema Hibernate then validates.
CREATE TABLE mission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    status      VARCHAR(255),
    start_time  TIMESTAMP(6) WITH TIME ZONE,
    end_time    TIMESTAMP(6) WITH TIME ZONE,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT mission_status_check CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'BIDDING', 'AWARDED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')
    )
);