-- Account table backing registration, login and profile.
-- Mirrors the entity com.project.drone_missions.data.model.User. The table is
-- named "users" (plural) because "user" is a reserved word in PostgreSQL.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT users_email_unique UNIQUE (email)
);
