CREATE TABLE bid (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id BIGINT NOT NULL,
    pilot_id   BIGINT NOT NULL,
    amount     NUMERIC(12, 2) NOT NULL,
    message    VARCHAR(500),
    status     VARCHAR(32) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- a mission's bids die with the mission (mission delete is a plain repository.delete)
    CONSTRAINT fk_bid_mission FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE,
    CONSTRAINT fk_bid_pilot FOREIGN KEY (pilot_id) REFERENCES users (id),
    -- one bid per pilot per mission; re-submitting updates the existing bid
    CONSTRAINT bid_mission_pilot_unique UNIQUE (mission_id, pilot_id),
    CONSTRAINT bid_status_check CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);

-- Awarding a bid records the winning pilot on the mission itself.
ALTER TABLE mission ADD COLUMN awarded_pilot_id BIGINT;
ALTER TABLE mission ADD CONSTRAINT fk_mission_awarded_pilot
    FOREIGN KEY (awarded_pilot_id) REFERENCES users (id);
