CREATE TABLE notification (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    type       VARCHAR(32) NOT NULL,
    title      VARCHAR(200) NOT NULL,
    message    VARCHAR(1000) NOT NULL,
    -- The mission this notification is about (nullable for non-mission notifications).
    mission_id BIGINT,
    -- Null while unread; set to the time the recipient marked it read.
    read_at    TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_mission FOREIGN KEY (mission_id) REFERENCES mission (id) ON DELETE CASCADE,
    CONSTRAINT notification_type_check CHECK (type IN ('BID_ACCEPTED', 'BID_REJECTED', 'MISSION_OVERDUE'))
);

-- Notifications are always listed per-recipient, newest first.
CREATE INDEX idx_notification_user_created ON notification (user_id, created_at DESC);
