import {
  bigint,
  boolean,
  check,
  date,
  foreignKey,
  index,
  jsonb,
  numeric,
  pgTable,
  smallint,
  timestamp,
  unique,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

/**
 * Drizzle schema mirror of the Flyway-owned Postgres schema.
 *
 * **Flyway owns the schema.** This file is a hand-written mirror of the
 * final shape produced by running `db/migration/V1__create_mission_table.sql`
 * through `V18__drop_mission_restored_audit_action.sql`, in order, against a
 * fresh database — it is never executed as a migration itself, and Drizzle
 * never runs `migrate`/`push` against a real database in this project.
 *
 * Canonical regeneration path (once a DB is migrated and reachable):
 *
 *   pnpm db:pull   (i.e. drizzle-kit pull --config=drizzle.config.ts)
 *
 * `drizzle-kit pull` introspects the live, Flyway-migrated database and
 * regenerates this file (and a snapshot) from the real catalog — that
 * output supersedes this hand-mirror the moment a database exists. Until
 * then, every table/column/constraint below was transcribed by reading all
 * 18 migration files, not by running `pull` (no DB is configured in this
 * environment yet). `pull`-regenerated output drops this header comment and
 * the `$type<...>()` string-literal-union narrowing below — both need to be
 * re-applied by hand after a real `pull`.
 *
 * CI drift guard: `pnpm db:check`, i.e. `node scripts/check-schema-drift.mjs`
 * — NOT bare `drizzle-kit check` (that command only validates a migration-
 * snapshot *history* against itself, never against a live database, and
 * this project never runs `drizzle-kit generate`/`migrate` for real, so that
 * history never exists here). The script instead runs `drizzle-kit generate`
 * against this file and `drizzle-kit introspect` against the live
 * DATABASE_URL, each into a throwaway temp dir, and deep-compares their
 * normalized snapshot JSON — immune to the comment/`$type<...>()` noise a
 * raw file diff would produce. See that script's header for the full
 * mechanism; wired into `.github/workflows/ci.yml` once DATABASE_URL is
 * available as a secret.
 *
 * This module intentionally has no `import "server-only"`: drizzle-kit's
 * `generate`/`introspect`/`push` CLIs load this file directly via `require`,
 * outside the `react-server` condition, and `server-only`'s guard throws
 * unconditionally in that context — it has no secrets or IO of its own to
 * guard against being bundled into a client component.
 *
 * Conventions ported from the migrations:
 * - Every PK is `BIGINT GENERATED BY DEFAULT AS IDENTITY` → `.generatedByDefaultAsIdentity()`.
 * - Every `TIMESTAMP(6) WITH TIME ZONE` → `timestamp(..., { precision: 6, withTimezone: true })`.
 * - Enum-shaped columns are plain `VARCHAR` + a `CHECK (col IN (...))` constraint in
 *   Postgres (no native `CREATE TYPE ... AS ENUM` was ever used) — mirrored here as a
 *   `varchar` column whose TS type is narrowed to a string-literal union via `.$type<...>()`,
 *   plus the matching `check()` builder so the constraint itself round-trips too.
 *
 * Source (read in full, V1 → V18):
 * drone-missions-backend/drone-missions/src/main/resources/db/migration/V1__create_mission_table.sql
 * … V18__drop_mission_restored_audit_action.sql
 */

// --- String-literal unions for CHECK-constrained columns ---

/** `mission_status_check` (V1), NOT NULL added by V2. */
export type MissionStatus =
  "DRAFT" | "PUBLISHED" | "BIDDING" | "AWARDED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
export const MISSION_STATUSES: MissionStatus[] = [
  "DRAFT",
  "PUBLISHED",
  "BIDDING",
  "AWARDED",
  "IN_PROGRESS",
  "COMPLETED",
  "CANCELLED",
];

/** `mission_moderation_check` (V13, tightened by V15 when REMOVED became a hard delete). */
export type MissionModeration = "VISIBLE" | "HIDDEN";
export const MISSION_MODERATIONS: MissionModeration[] = ["VISIBLE", "HIDDEN"];

/** `users_role_check` (V5, widened by V12 to add ADMIN). */
export type UserRole = "DESIGNER" | "PILOT" | "ADMIN";
export const USER_ROLES: UserRole[] = ["DESIGNER", "PILOT", "ADMIN"];

/** `bid_status_check` (V8). */
export type BidStatus = "PENDING" | "ACCEPTED" | "REJECTED";
export const BID_STATUSES: BidStatus[] = ["PENDING", "ACCEPTED", "REJECTED"];

/** `notification_type_check` (V9, widened by V10 to add MISSION_CANCELLED). */
export type NotificationType =
  "BID_ACCEPTED" | "BID_REJECTED" | "MISSION_OVERDUE" | "MISSION_CANCELLED";
export const NOTIFICATION_TYPES: NotificationType[] = [
  "BID_ACCEPTED",
  "BID_REJECTED",
  "MISSION_OVERDUE",
  "MISSION_CANCELLED",
];

/** `audit_log_actor_role_check` (V14) — same domain as UserRole, kept separate per-column. */
export type AuditActorRole = "DESIGNER" | "PILOT" | "ADMIN";
export const AUDIT_ACTOR_ROLES: AuditActorRole[] = ["DESIGNER", "PILOT", "ADMIN"];

/** `audit_log_target_type_check` (V14). */
export type AuditTargetType = "MISSION" | "BID" | "USER" | "RATING";
export const AUDIT_TARGET_TYPES: AuditTargetType[] = ["MISSION", "BID", "USER", "RATING"];

/**
 * `audit_log_action_check` (V14, widened by V17 to add ADMIN_CREATED, then V18 drops
 * MISSION_RESTORED — this is the final V18 shape).
 */
export type AuditAction =
  | "MISSION_CREATED"
  | "MISSION_UPDATED"
  | "MISSION_DELETED"
  | "MISSION_STARTED"
  | "MISSION_COMPLETED"
  | "MISSION_CANCELLED"
  | "MISSION_HIDDEN"
  | "MISSION_UNHIDDEN"
  | "MISSION_REMOVED"
  | "BID_PLACED"
  | "BID_WITHDRAWN"
  | "BID_ACCEPTED"
  | "USER_REGISTERED"
  | "USER_LOGGED_IN"
  | "USER_SUSPENDED"
  | "USER_REACTIVATED"
  | "ADMIN_CREATED"
  | "RATING_CREATED";
export const AUDIT_ACTIONS: AuditAction[] = [
  "MISSION_CREATED",
  "MISSION_UPDATED",
  "MISSION_DELETED",
  "MISSION_STARTED",
  "MISSION_COMPLETED",
  "MISSION_CANCELLED",
  "MISSION_HIDDEN",
  "MISSION_UNHIDDEN",
  "MISSION_REMOVED",
  "BID_PLACED",
  "BID_WITHDRAWN",
  "BID_ACCEPTED",
  "USER_REGISTERED",
  "USER_LOGGED_IN",
  "USER_SUSPENDED",
  "USER_REACTIVATED",
  "ADMIN_CREATED",
  "RATING_CREATED",
];

// --- Tables ---

/**
 * users (V3__Create_users_table.sql)
 * + role (V5, CHECK widened V12), suspended (V16 — replaces V13's suspended_at timestamp).
 * Named plural because "user" is a reserved word in Postgres.
 */
export const users = pgTable(
  "users",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    username: varchar("username", { length: 255 }).notNull(),
    email: varchar("email", { length: 255 }).notNull(),
    passwordHash: varchar("password_hash", { length: 255 }).notNull(),
    role: varchar("role", { length: 32 }).notNull().$type<UserRole>(),
    suspended: boolean("suspended").notNull().default(false),
    createdAt: timestamp("created_at", { precision: 6, withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { precision: 6, withTimezone: true }).notNull(),
  },
  (table) => [
    unique("users_email_unique").on(table.email),
    check("users_role_check", sql`${table.role} IN ('DESIGNER', 'PILOT', 'ADMIN')`),
  ],
);

/**
 * mission (V1__create_mission_table.sql)
 * + user_id (V4), role/status NOT NULL (V2), description widened to 2000 (V6),
 * + location/bidding_deadline/waypoints/geofence (V7), awarded_pilot_id (V8),
 * + moderation (V13, CHECK tightened V15).
 */
export const mission = pgTable(
  "mission",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    name: varchar("name", { length: 255 }),
    description: varchar("description", { length: 2000 }),
    status: varchar("status", { length: 255 }).notNull().$type<MissionStatus>(),
    startTime: timestamp("start_time", { precision: 6, withTimezone: true }),
    endTime: timestamp("end_time", { precision: 6, withTimezone: true }),
    createdAt: timestamp("created_at", { precision: 6, withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { precision: 6, withTimezone: true }).notNull(),
    userId: bigint("user_id", { mode: "number" }),
    location: varchar("location", { length: 255 }),
    biddingDeadline: date("bidding_deadline"),
    /** Ordered list of route waypoints — variable-shape, stored as JSONB (V7). */
    waypoints: jsonb("waypoints"),
    /** A circle OR a polygon flight zone — variable-shape, stored as JSONB (V7). */
    geofence: jsonb("geofence"),
    awardedPilotId: bigint("awarded_pilot_id", { mode: "number" }),
    moderation: varchar("moderation", { length: 16 })
      .notNull()
      .default("VISIBLE")
      .$type<MissionModeration>(),
  },
  (table) => [
    foreignKey({
      name: "fk_mission_user",
      columns: [table.userId],
      foreignColumns: [users.id],
    }),
    foreignKey({
      name: "fk_mission_awarded_pilot",
      columns: [table.awardedPilotId],
      foreignColumns: [users.id],
    }),
    check(
      "mission_status_check",
      sql`${table.status} IN ('DRAFT', 'PUBLISHED', 'BIDDING', 'AWARDED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`,
    ),
    check("mission_moderation_check", sql`${table.moderation} IN ('VISIBLE', 'HIDDEN')`),
  ],
);

/** bid (V8__create_bid_table.sql) */
export const bid = pgTable(
  "bid",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    missionId: bigint("mission_id", { mode: "number" }).notNull(),
    pilotId: bigint("pilot_id", { mode: "number" }).notNull(),
    amount: numeric("amount", { precision: 12, scale: 2 }).notNull(),
    message: varchar("message", { length: 500 }),
    status: varchar("status", { length: 32 }).notNull().$type<BidStatus>(),
    createdAt: timestamp("created_at", { precision: 6, withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { precision: 6, withTimezone: true }).notNull(),
  },
  (table) => [
    // A mission's bids die with the mission (mission delete is a plain repository.delete).
    foreignKey({
      name: "fk_bid_mission",
      columns: [table.missionId],
      foreignColumns: [mission.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_bid_pilot",
      columns: [table.pilotId],
      foreignColumns: [users.id],
    }),
    // One bid per pilot per mission; re-submitting updates the existing bid.
    unique("bid_mission_pilot_unique").on(table.missionId, table.pilotId),
    check("bid_status_check", sql`${table.status} IN ('PENDING', 'ACCEPTED', 'REJECTED')`),
  ],
);

/** notification (V9__create_notification_table.sql), type CHECK widened by V10. */
export const notification = pgTable(
  "notification",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    userId: bigint("user_id", { mode: "number" }).notNull(),
    type: varchar("type", { length: 32 }).notNull().$type<NotificationType>(),
    title: varchar("title", { length: 200 }).notNull(),
    message: varchar("message", { length: 1000 }).notNull(),
    /** The mission this notification is about (nullable for non-mission notifications). */
    missionId: bigint("mission_id", { mode: "number" }),
    /** Null while unread; set to the time the recipient marked it read. */
    readAt: timestamp("read_at", { precision: 6, withTimezone: true }),
    createdAt: timestamp("created_at", { precision: 6, withTimezone: true }).notNull(),
    updatedAt: timestamp("updated_at", { precision: 6, withTimezone: true }).notNull(),
  },
  (table) => [
    foreignKey({
      name: "fk_notification_user",
      columns: [table.userId],
      foreignColumns: [users.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_notification_mission",
      columns: [table.missionId],
      foreignColumns: [mission.id],
    }).onDelete("cascade"),
    check(
      "notification_type_check",
      sql`${table.type} IN ('BID_ACCEPTED', 'BID_REJECTED', 'MISSION_OVERDUE', 'MISSION_CANCELLED')`,
    ),
    // Notifications are always listed per-recipient, newest first.
    index("idx_notification_user_created").on(table.userId, table.createdAt.desc()),
  ],
);

/** rating (V11__create_rating_table.sql) */
export const rating = pgTable(
  "rating",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    missionId: bigint("mission_id", { mode: "number" }).notNull(),
    raterId: bigint("rater_id", { mode: "number" }).notNull(),
    rateeId: bigint("ratee_id", { mode: "number" }).notNull(),
    score: smallint("score").notNull(),
    comment: varchar("comment", { length: 500 }),
    createdAt: timestamp("created_at", { precision: 6, withTimezone: true }).notNull(),
  },
  (table) => [
    foreignKey({
      name: "fk_rating_mission",
      columns: [table.missionId],
      foreignColumns: [mission.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "fk_rating_rater",
      columns: [table.raterId],
      foreignColumns: [users.id],
    }),
    foreignKey({
      name: "fk_rating_ratee",
      columns: [table.rateeId],
      foreignColumns: [users.id],
    }),
    // One rating per rater per mission: this is what makes a rating final.
    unique("rating_mission_rater_unique").on(table.missionId, table.raterId),
    check("rating_score_check", sql`${table.score} BETWEEN 1 AND 5`),
    // Profile lookups are all "ratings received by this user".
    index("idx_rating_ratee").on(table.rateeId),
  ],
);

/**
 * audit_log (V14__create_audit_log.sql), action CHECK widened by V17 (ADMIN_CREATED),
 * then narrowed by V18 (MISSION_RESTORED dropped, and its historical rows purged).
 * Insert-only (no updated_at). The actor is a real FK with no cascade — users are
 * never deleted, and history must never be erasable through a user row. The target
 * is a (type, id) pair, not an FK, since missions/bids/etc. are deletable and the
 * history has to outlive them.
 */
export const auditLog = pgTable(
  "audit_log",
  {
    id: bigint("id", { mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    actorId: bigint("actor_id", { mode: "number" }).notNull(),
    actorRole: varchar("actor_role", { length: 16 }).notNull().$type<AuditActorRole>(),
    action: varchar("action", { length: 32 }).notNull().$type<AuditAction>(),
    targetType: varchar("target_type", { length: 16 }).notNull().$type<AuditTargetType>(),
    targetId: bigint("target_id", { mode: "number" }).notNull(),
    details: varchar("details", { length: 500 }),
    createdAt: timestamp("created_at", { precision: 6, withTimezone: true }).notNull(),
  },
  (table) => [
    foreignKey({
      name: "fk_audit_log_actor",
      columns: [table.actorId],
      foreignColumns: [users.id],
    }),
    check("audit_log_actor_role_check", sql`${table.actorRole} IN ('DESIGNER', 'PILOT', 'ADMIN')`),
    check(
      "audit_log_target_type_check",
      sql`${table.targetType} IN ('MISSION', 'BID', 'USER', 'RATING')`,
    ),
    check(
      "audit_log_action_check",
      sql`${table.action} IN (
      'MISSION_CREATED', 'MISSION_UPDATED', 'MISSION_DELETED', 'MISSION_STARTED',
      'MISSION_COMPLETED', 'MISSION_CANCELLED', 'MISSION_HIDDEN', 'MISSION_UNHIDDEN',
      'MISSION_REMOVED',
      'BID_PLACED', 'BID_WITHDRAWN', 'BID_ACCEPTED',
      'USER_REGISTERED', 'USER_LOGGED_IN', 'USER_SUSPENDED', 'USER_REACTIVATED',
      'ADMIN_CREATED',
      'RATING_CREATED')`,
    ),
    // The admin listing is always newest-first; the actor filter narrows the same path.
    index("idx_audit_log_created").on(table.createdAt.desc()),
    index("idx_audit_log_actor_created").on(table.actorId, table.createdAt.desc()),
  ],
);
